// @ts-nocheck
// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY IT.

import { Asset, Entry } from "contentful";
import { Document } from "@contentful/rich-text-types";

export interface IAnimalFields {
  /** Imię */
  name: string;

  /** Rodzaj */
  type: "pies" | "kot";

  /** Płeć */
  gender: "ona" | "on";

  /** Zwierzę właścicielskie */
  ownerPet?: boolean | undefined;

  /** Adres */
  location?: string | undefined;

  /** Data urodzenia */
  dateOfBirth?: string | undefined;

  /** Waga (kg) */
  weight?: string | undefined;

  /** Ma dom tymczasowy? */
  temporaryHome?: boolean | undefined;

  /** Został adoptowany? */
  adopted?: boolean | undefined;

  /** Aktywność */
  activityLevel?:
    | "kanapowiec"
    | "średnio aktywny"
    | "potrzebuje dużo ruchu"
    | undefined;

  /** Zdrowie */
  health?:
    | (
        | "szczepiony"
        | "odrobaczony"
        | "w trakcie leczenia"
        | "wymaga leczenia długofalowego"
        | "niepełnosprawny"
        | "po kastracji/sterylizacji"
      )[]
    | undefined;

  /** Relacje */
  behavior?:
    | (
        | "akceptuje psy"
        | "akceptuje koty"
        | "akceptuje małe dzieci"
        | "akceptuje nastolatki"
        | "przyjazny dla wszystkich"
      )[]
    | undefined;

  /** Informacje dodatkowe */
  additionalInfo?:
    | (
        | "wymaga pracy z behawiorystą"
        | "wymaga windy / braku schodów"
        | "lęk separacyjny"
        | "zachowuje czystość w domu"
      )[]
    | undefined;

  /** Główne zdjęcie */
  thumbnail: Asset;

  /** Krótki opis */
  excerpt: string;

  /** Opis */
  description?: Document | undefined;

  /** Kogo szuka? */
  idealFamily?: Document | undefined;

  /** Zdjęcia */
  images: Asset[];

  /** Slug */
  slug: string;
}

/** Zwierzęta, które były lub dalej są w fundacji. */

export interface IAnimal extends Entry<IAnimalFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "animal";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IFaqFields {
  /** Pytanie */
  question: string;

  /** Kategoria */
  category:
    | "Adopcja"
    | "Dom tymczasowy"
    | "Wsparcie finansowe"
    | "Wsparcie rzeczowe"
    | "Wolontariat";

  /** Odpowiedź */
  answer: Document;
}

/** Najczęściej zadawane pytania. */

export interface IFaq extends Entry<IFaqFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "faq";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IFinancialStatementFields {
  /** Nazwa */
  name: string;

  /** Link */
  url?: string | undefined;
}

export interface IFinancialStatement extends Entry<IFinancialStatementFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "financialStatement";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IGlobalFields {
  /** Tytuł strony */
  pageTitle: string;

  /** Email */
  email: string;

  /** Facebook Link */
  facebook?: string | undefined;

  /** Instagram Link */
  instagram?: string | undefined;

  /** Ratujemy Zwierzaki link */
  fundraisingLink?: string | undefined;

  /** Numer konta bankowego */
  accountNumber: string;

  /** Numer NIP */
  nip: string;

  /** Numer KRS */
  krs: string;

  /** Adres (ulica) */
  address: string;

  /** Adres (kod pocztowy, miasto) */
  city: string;

  /** Ankieta przedadopcyjna (link) */
  preAdoptionSurveyLink: string;

  /** Ankieta dla domu tymczasowego (link) */
  temporaryHomeSurveyLink?: string | undefined;

  /** Umowa adopcyjna (link) */
  adoptionAgreement?: string | undefined;

  /** Umowa dla domu tymczasowego (link) */
  temporaryHomeAgreement?: string | undefined;
}

/** Globalne informacje o fundacji. */

export interface IGlobal extends Entry<IGlobalFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "global";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface ILinkFields {
  /** Nazwa */
  name?: string | undefined;

  /** URL */
  url?: string | undefined;
}

export interface ILink extends Entry<ILinkFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "link";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IPartnershipFields {
  /** Tytuł */
  title: string;

  /** Zdjęcie */
  image: Asset;

  /** Wielkość zniżki */
  discount?: string | undefined;

  /** Opis */
  description?: string | undefined;

  /** Tylko dla rodzin adopcyjnych? */
  adoptionFamilyOnly?: boolean | undefined;

  /** Link */
  url: string;

  /** Kod promocyjny */
  discountCode?: string | undefined;

  /** Pokazać logo na głównej stronie w Nasi Partnerzy ? */
  showLogoInPartners: boolean;
}

/** Współprace, partnerzy i zniżki. */

export interface IPartnership extends Entry<IPartnershipFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "partnership";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IPeopleFields {
  /** Imię i nazwisko */
  name: string;

  /** Numer telefonu */
  phoneNumber?: string | undefined;

  /** W zarządzie fundacji? */
  inManagement: boolean;

  /** Stanowisko */
  position?: string | undefined;

  /** Czy to osoba do kontaktu? */
  contactPerson?: boolean | undefined;

  /** Zdjęcie */
  image?: Asset | undefined;
}

export interface IPeople extends Entry<IPeopleFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "people";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface ITestimonialFields {
  /** Tytuł */
  title: string;

  /** Opis */
  description: string;

  /** Autor */
  author: string;

  /** Autor (opis) */
  authorDescription?: string | undefined;
}

export interface ITestimonial extends Entry<ITestimonialFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "testimonial";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IVolunteerNeedFields {
  /** Name */
  name: string;

  /** Aktualnie poszukiwany? */
  active: boolean;

  /** Opis */
  description: string;
}

export interface IVolunteerNeed extends Entry<IVolunteerNeedFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "volunteerNeed";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export type CONTENT_TYPE =
  | "animal"
  | "faq"
  | "financialStatement"
  | "global"
  | "link"
  | "partnership"
  | "people"
  | "testimonial"
  | "volunteerNeed";

export type IEntry =
  | IAnimal
  | IFaq
  | IFinancialStatement
  | IGlobal
  | ILink
  | IPartnership
  | IPeople
  | ITestimonial
  | IVolunteerNeed;

export type LOCALE_CODE = "pl-PL";

export type CONTENTFUL_DEFAULT_LOCALE_CODE = "pl-PL";
